version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: next
    schedule:
      interval: weekly
      day: friday
    labels:
      - dependencies
    groups:
      all-npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: next
    schedule:
      interval: weekly
      day: friday
    labels:
      - dependencies
    groups:
      all-actions:
        patterns:
          - "*"
